### ISSUE TITLE
[WIP] Refactoring

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/ci-dnf-stack#124]
- Split actions into:
  - ☑ build-srpm (Build SRPM)
  - ☐ build-rpm (Build RPM)
    - ☑ rpmbuild
    - ☐ mock
    - ☑ copr
  - ☐ run-tests (Run tests)
    - ☐ local (Run all tests locally without any kind of using docker, etc.)
    - ☐ docker (The same as local, but everything in docker)

- Split jenkins jobs (`job-template` in JJB) to be able to see in which combinations what is failing:
  - ☐ by fedora versions (`fedora-rawhide-x86_64`, `fedora-rawhide-i386`, etc.)
  - ☐ by python versions (`dnf-2`, `dnf-3`)

- ☐ Use only python bindings instread of `subprocess` for docker (`docker-py`)

- ☑ Get rid out of httpd and use python's `http.server`

- Make code python3 compatible
  - ☑ Main tool
  - ☐ Tests

- ☐ Use JUint output from behave to integrate test results into Jenkins (instead of spawning shell 100500 times and counting tests by retcode without catching output properly)

- ☑ Use version 2 of COPR API

**Comment by j-mracek** [comment]
Interesting. Some steps are probably not so hot.

**Comment by ignatenkobrain** [comment]
let's split it into different bugs
