### ISSUE TITLE
Overquoting removed from modulemd-defaults documents in developmental libmodulemd

### ISSUE THREAD

**Issue by ppisar** [rpm-software-management/ci-dnf-stack#1273]
In 18af1075d641d534a9e2f95b59c76b9b848ec7e2 commit you adapted tests to stronger quoting of YAML scalars introduced in libmodulemd <https://github.com/fedora-modularity/libmodulemd/pull/587>. Since it means you run DNF tests against developmental libmodulemd, I notify you that few minutes ago I mostly restored the quoting to a state before that change.

It means you can mostly revert that 18af1075d641d534a9e2f95b59c76b9b848ec7e2 commit. Though new quoting around number-like values can appear anywhere now, I recommend you rerunning tests to catch all the changes. A long term goal for libmodulemd is only quote those YAML values which could be mistaken with a number.

**Comment by kontura** [comment]
Thanks for the heads up.
We have updated our tests.
