### ISSUE TITLE
Extend functions for parsing transactions (dnf5)

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/ci-dnf-stack#1344]
parse_transaction_table_dnf5 function in dnf/steps/lib/dnf.py currently ends up with a traceback when the parsed transaction table contains "Changing reason:" section, e.g.
~~~
      Package                       Arch   Version      Repository         Size
      Changing reason:                                                         
       filesystem                   x86_64 3.9-2.fc29   @System         0.0   B
         Group -> Dependency                                                   
~~~
Also, a specification of expected behavior in such a case is needed (e.g. whether the exact type of changed reason should be somehow captured in test scenarios or not).

**Comment by kontura** [comment]
I have a version of this locally as a part of transaction replay work but it will likely take a while before its all ready. 
Do you need this rather soon? I could extract it into a separate PR.

In my version it doesn't track how the reasons changed only that there was a change for a specified package. However it is possible to check the resulting reason with `Then dnf5 transaction items for transaction "last" are` step.

**Comment by glum23** [comment]
@kontura I just wanted to update all `dnf5 group` related tests, it can be done later. I agree that it's not necessary to track here how the reasons changed.

**Comment by kontura** [comment]
This is now resolved by: https://github.com/rpm-software-management/ci-dnf-stack/commit/3eb27b3801350adade724e1a0eff873118c85e41
