### ISSUE TITLE
Get rid out of httpd and use python's http.server/SimpleHTTPServer

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/ci-dnf-stack#138]
Profits:
- Faster container building
- Don't need to support a huge conffile
- A bit faster start
- .. Probably some more

@j-mracek @jsilhan @mluscon thoughts?

**Comment by mluscon** [comment]
Do you have exact numbers for #1?

**Comment by j-mracek** [comment]
According to 2# The httpd should work with default conf, therefore no need to maintain. I also know that httpd is used by QE, but no idea if they use python's http.server.

**Comment by ignatenkobrain** [comment]
@mluscon hm, it;s not much... about 1-2 mins
@j-mracek should work != what we have now (own config).

Why I want to have python http server is that it's easier to run it from any directory which means I can easily host repo in any time without removing/copying files into /repo.

**Comment by j-mracek** [comment]
@ignatenkobrain That is incorrect. The repos are not copy during run. Only RPMs are and only for purpose of install by rpm (rich tests).
I have also doubs, how it will work outside of behave script. When I will enter docker, run test that fails and behave exits. Will be http server still available?

**Comment by j-mracek** [comment]
@ignatenkobrain Lets say like that, there is no issue with httpd so far. You want to introduce new staff. Fine, but first you have to be 100% sure that new approach will provide same functionality like last one. That mean really every usage not only during test run, but also for debugging inside of docker. At this point this is neutral change (with some risk), with no significant profit. Is it really worth to change it?
From other hand if installation of additional package take 1-2 min for dnf, we have to fix it in dnf.
