### ISSUE TITLE
Information about rpm build

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/ci-dnf-stack#162]
Can we see what package failed or succeed during rpm-build in console? Like:

2016-06-27 14:53:43,925:INFO: Build #363102: succeeded - dnf-2.0.0.1-dsfdfssdf-f24.rpm
2016-06-27 14:53:43,925:INFO: Build #363102: failed - dnf-2.0.0.1-dsfdfssdf.srpm.rpm

**Comment by ignatenkobrain** [comment]
please report this to https://github.com/ignatenkobrain/rpm-gitoverlay

**Comment by j-mracek** [comment]
@ignatenkobrain Please what is relationship between ci-dnf-stack and gitoverlay. ci-dnf-stack is not the upstream?

**Comment by ignatenkobrain** [comment]
@j-mracek nope, ci-dnf-stack uses rpm-gitoverlay which is totally different project.
