### ISSUE TITLE
do not run dnf-2 and dnf-3 tests in parallel

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/ci-dnf-stack#275]
to get reasonable time of running tests we should run dnf-2 and dnf-3 tests sequentially.

**Comment by ignatenkobrain** [comment]
running whole thing in parallel just makes server overloaded and testing time sometimes goes over 10 minutes.

**Comment by j-mracek** [comment]
We have to run it anyway

**Comment by ignatenkobrain** [comment]
@j-mracek in sequential order it will not overload server

**Comment by j-mracek** [comment]
Because we stop to run dnf-2 tests therefore I consider the issue not valid anymore.
