### ISSUE TITLE
extend "Given repository {repo} with packages" to support scriptlets 

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/ci-dnf-stack#281]
for testing some features we need to have rpms with scriptlets, there's currently no support for that in the testsuite

**Comment by ignatenkobrain** [comment]
do you have some example of scriptlets which you would like to have?

**Comment by glum23** [comment]
@ignatenkobrain simple ones, see e.g. /CoreOS/yum/Sanity/bz856969-scriptlet-output-and-warnings

**Comment by kkaarreell** [comment]
Basically we would be mostly testing only scriptlet failures so the typical script would be something like "exit 1".

**Comment by kkaarreell** [comment]
I am closing this issue as the support has been implemented via https://github.com/rpm-software-management/ci-dnf-stack/pull/284
