### ISSUE TITLE
rpm_steps.py: extend functionality of "rpmdb changes are"

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/ci-dnf-stack#304]
Sometimes it'd be useful not to check all the changes of rpmdb but only a subset of them (e.g. when gpg-pubkey packages are installed as a consequence of common package installation, packages are installed using wildcards, etc.). In such cases it's possible to call "rpm -q" instead of "rpmdb changes are" to workaround it, however, it's not a clear approach. Would it be possible to add a special state to step_rpmdb_changes_are ensuring that the rest of changes not listed previously are ignored?

**Comment by kkaarreell** [comment]
I have discussed this feature request with Igor and we agreed that adding a state Ignoring that allows user to specify packages using wildcards is a reasonable way to go.

**Comment by kkaarreell** [comment]
Should be implemented in PR https://github.com/rpm-software-management/ci-dnf-stack/pull/306
