### ISSUE TITLE
create step for matching the key/value pairs for an ini file

### ISSUE THREAD

**Issue by kkaarreell** [rpm-software-management/ci-dnf-stack#336]
For various use cases (like checking the repo file or module config file) we would need a step that let's us to check that there is a specific key/value pair in a respective section.

Something like:
```
(step) an INI file {filepath} does contain
  | Section | Key | Value |
  | main    | foo | bar   |       
```

**Comment by ignatenkobrain** [comment]
Do you have example how you want to use this?

**Comment by kkaarreell** [comment]
In case some command is suppose to alter an INI file, I need comfortable way to verify the content.
Example from a yum world. yum-config-manager can enable/disable specific repositories. To test that functionality, I need to be able to check that the respective key (enabled) has the right value (0/False/etc.).

**Comment by ignatenkobrain** [comment]
@kkaarreell I think config-manager is bad example.

**Comment by kkaarreell** [comment]
Why?

**Comment by kkaarreell** [comment]
Implementation attempt in https://github.com/rpm-software-management/ci-dnf-stack/pull/344

**Comment by kkaarreell** [comment]
Implemented.
